Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2021-12, with the labels that each got.

#52 Quickstart patch release
  quickstart.rb
Labels: approved, size/XS, lgtm

#53 Fix owners file to reference aliases
  OWNERS
Labels: approved, size/S, lgtm

#51 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/S, lgtm

#54 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#56 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm
