Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2021-04, with the labels that each got.

#5 added v0.22 formulas
  admin@0.22.rb
  source-kafka@0.22.rb
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#13 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test

#14 Typo
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
