Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2021-09, with the labels that each got.

#31 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/M, lgtm

#32 Add kn-plugin-func formula
  func.rb
Labels: cla: yes, approved, size/M, lgtm

#33 Add func to readme
  README.md
Labels: cla: yes, approved, size/XS, lgtm

#34 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/M, lgtm

#37 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/S, lgtm

#40 Rename classes causing quickstart installation to fail
  admin@0.25.rb
  source-kafka@0.25.rb
Labels: cla: yes, approved, size/XS, lgtm
