Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2021-11, with the labels that each got.

#46 Fix version numbers for 1.0
  admin.rb
  quickstart.rb
  source-kafka.rb
  source-kamelet.rb
Labels: cla: yes, approved, size/S, lgtm

#48 Fixing bug with 0.26 formulas
  admin@0.26.rb
  source-kafka@0.26.rb
  source-kamelet@0.26.rb
Labels: cla: yes, approved, size/XS, lgtm

#44 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/M, lgtm

#49 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm
