Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2022-04, with the labels that each got.

#73 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#75 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#76 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#79 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#80 chore: fix cpu lookup for func
  func.rb
Labels: approved, kind/bug, size/XS, lgtm

#81 chore: use uname to lookup arch in func.rb
  func.rb
Labels: approved, size/S, lgtm
