Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2022-05, with the labels that each got.

#82 Update func@0.22 class name
  func@0.22.rb
Labels: approved, size/XS, lgtm

#84 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#83 Add homebrew-kn-plugins-approvers to owners
  OWNERS
Labels: approved, size/XS, lgtm

#85 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#86 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#87 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#88 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
