Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2022-06, with the labels that each got.

#90 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#91 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#93 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#94 Add script to update plugin versions
  README.md
  hack/update-versions.sh
Labels: ok-to-test, approved, size/M, lgtm

#95 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#96 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#97 Allows setting versions on command line for update script
  hack/update-versions.sh
Labels: approved, size/XS, lgtm
