Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2022-01, with the labels that each got.

#58 Update quickstart plugin to v1.1.1
  quickstart.rb
Labels: approved, size/XS, lgtm

#57 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/S, lgtm

#60 :gift: Adding kn-event plugin
  .github/workflows/knative-rspec-test.yaml
  .gitignore
  .rspec
  Gemfile
  Gemfile.lock
  README.md
  event.rb
  kn/checksums.rb
  kn/net/downloader.rb
  kn/os.rb
  kn/plugin/event.rb
  spec/kn/checksums_spec.rb
  spec/kn/plugin/event_spec.rb
Labels: approved, size/L, kind/enhancement, lgtm
