Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2023-01, with the labels that each got.

#130 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#127 chore(func): bump latest func to 1.8.1
  func.rb
Labels: approved, size/S, lgtm

#131 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
