Repository knative-extensions/homebrew-kn-plugins, pull requests merged in 2024-02, with the labels that each got.

#179 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#180 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#181 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#182 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#183 Add script and GH action to verify taps
  .github/workflows/knative-homebrew-test.yaml
  func@0.25.rb
  func@0.26.rb
  func@1.7.rb
  func@1.8.rb
  hack/verify-taps.sh
  quickstart@1.7.rb
  source-kafka@1.7.rb
Labels: approved, size/L, lgtm
